CREATE TABLE [fact].[StudentSchedule] (
    [StudentSchedule_ID]                          INT           IDENTITY (1, 1) NOT NULL,
    [AcademicYear_Key]                            INT           NOT NULL,
    [School_Key]                                  INT           NOT NULL,
    [Student_Key]                                 INT           NOT NULL,
    [Course_Key]                                  INT           NOT NULL,
    [Term]                                        VARCHAR (12)  NULL,
    [SectionID]                                   VARCHAR (20)  NULL,
    [ContentAreaCode]                             VARCHAR (3)   NULL,
    [ContentAreaName]                             VARCHAR (250) NULL,
    [CTECIPCode]                                  CHAR (6)      NULL,
    [CTECIPName]                                  VARCHAR (250) NULL,
    [CTEClusterID]                                VARCHAR (3)   NULL,
    [CTEClusterName]                              VARCHAR (250) NULL,
    [CTEPathwayID]                                VARCHAR (3)   NULL,
    [CTEPathwayName]                              VARCHAR (250) NULL,
    [TechPrepCourseFlag]                          SMALLINT      NULL,
    [InternationalBaccalaureateFlag]              SMALLINT      NULL,
    [CollegeattheHighSchoolFlag]                  SMALLINT      NULL,
    [HonorsFlag]                                  SMALLINT      NULL,
    [AdvancedPlacementFlag]                       SMALLINT      NULL,
    [RunningStartFlag]                            SMALLINT      NULL,
    [CollegeAcademicDistributionRequirementsFlag] SMALLINT      NULL,
    [CambridgeProgramFlag]                        SMALLINT      NULL,
    [OnlineFlag]                                  SMALLINT      NULL,
    [DataLoadID]                                  INT           NULL,
    [LoadDate]                                    DATETIME      NULL,
    [IsCurrent]                                   BIT           CONSTRAINT [DF_StudentSchedule_IsCurrent] DEFAULT ((1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([StudentSchedule_ID] ASC),
    --CONSTRAINT [fk_Schedule_StudentKey] FOREIGN KEY ([Student_Key]) REFERENCES [dim].[Student] ([Student_Key]),
    --CONSTRAINT [fk_Schedule_CourseKey] FOREIGN KEY ([Course_Key]) REFERENCES [dim].[Course] ([Course_Key]),
    --CONSTRAINT [fk_Schedule_AcademicYearKey] FOREIGN KEY ([AcademicYear_Key]) REFERENCES [dim].[AcademicYear] ([AcademicYear_Key]),
    --CONSTRAINT [fk_Schedule_SchoolKey] FOREIGN KEY ([School_Key]) REFERENCES [dim].[School] ([School_Key])
);
